cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hw/', include('hw.urls')),
    path('quotes/', include('quotes.urls')),
    path('formdata/', include('formdata.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('blog/', include('blog.urls')),
    path('mini_fb/', include('mini_fb.urls')),
    path('marathon_analytics/', include('marathon_analytics.urls')),
    path('voter_analytics/', include('voter_analytics.urls')),
    path('project/', include('project.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hw/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
   # path(r'', views.home, name = "home"),
   path(r'', views.home_page, name  = "home_page"),
   path(r'about', views.about, name = "about_page"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/urls.py
#urls.py holds urlpatterns for page navigation for the
#online car dealership

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(r'', views.HomepageView.as_view(), name = 'home'),
    path(r'homepage', views.HomepageView.as_view(), name = 'home_page'),
    path(r'vehicles', views.VehicleListView.as_view(), name='vehicle_list'),
    path(r'salespeople', views.SalespersonListView.as_view(), name = 'salespeople'),
    path(r'vehicle_details/<int:pk>', views.VehicleDetailView.as_view(), name = 'vehicle_details'),
    path(r'customers', views.CustomerListView.as_view(), name = 'customers'),
    path(r'customer_details/<int:pk>', views.CustomerDetailView.as_view(), name='customer_details'),
    path(r'customer_details/<int:pk>/create_offer', views.CreateSalesMatchView.as_view(), name='create_offer'),
    path(r'login', auth_views.LoginView.as_view(template_name = 'project/login.html'), name='login'),
    path(r'logout', auth_views.LogoutView.as_view(template_name='project/logout.html'), name='logout'),
    path(r'salesmatch_details/<int:pk>', views.SalesMatchDetailView.as_view(), name='salesmatch_detail'),
    path(r'salesmatches', views.SalesmatchListView.as_view(), name = 'salesmatch_list'),
    path(r'salesmatch_details/<int:pk>/update', views.UpdateSalesmatchView.as_view(), name="update_salesmatch"),
    path(r'offer_rejected', views.OfferRejectedView.as_view(), name = 'offer_rejected'),
    path(r'offer_accepted', views.OfferAcceptedView.as_view(), name = 'offer_accepted'),
    path(r'salesmatch_details/<int:pk>/decision', views.OfferDecisionView.as_view(), name = 'offer_decision'),
    path(r'vehicle_details/<int:pk>/interest', views.ExpressInterestView.as_view(), name = 'express_interest'),
    path(r'sold_vehicles', views.SoldVehicleListView.as_view(), name="sold_vehicles"),
    path(r'wrong_passkey', views.InvalidPasskeyView.as_view(), name='invalid_passkey'),
    path(r'register/customer', views.CreateCustomerView.as_view(), name = 'register_customer'),
    path(r'register/salesperson', views.CreateSalespersonView.as_view(), name = 'register_salesperson'),
    path(r'delete_account', views.DeleteAccountView.as_view(), name = 'delete_account'),
    path(r'add_vehicle', views.CreateVehicleView.as_view(), name="add_vehicle"),
    path(r'salesperson_details/<int:pk>/review', views.CreateSalespersonReview.as_view(), name = "salesperson_review"),
    path(r'salesperson_details/<int:pk>', views.SalespersonDetailView.as_view(), name = "salesperson_details"),
    path(r'salesperson_details/<int:pk>/update', views.UpdateSalesReview.as_view(), name = 'update_sales_review'),
    path(r'salesperson_details/<int:pk>/delete', views.DeleteSalesReview.as_view(), name = 'delete_sales_review'),
    

]

project/models.py
#models for the final project (car dealership)
#contains definitions for Vehicles, Customers, Salespeople
#SalesMatches (pending sales), SalesReviews
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Vehicle(models.Model):
    '''model representing a vehicle at the car dealership
    includes VIN, make, model, year, body type (SUV, sedan, etc)
    , engine size (num cylinders), average MPG, and msrp and a field for 
    determining if the vehicle is sold'''

    vin = models.TextField(blank = False)
    make = models.TextField(blank = False)
    model = models.TextField(blank = False)
    year = models.IntegerField(blank = False)
    body_type = models.TextField(blank = False)
    engine_size = models.IntegerField(blank = False)
    mpg = models.IntegerField(blank = False)
    msrp = models.IntegerField(blank = False)
    image = models.ImageField(blank = True)
    isSold = models.BooleanField(default = False)   #set a default value for new vehicles

def load_data():
    '''a function to create model instances from a 
    csv (Vehicle)
    The CSV used included 17 makes, each having multiple objects of the
    same vehicle to save time while creating a populous database'''
    #delete all entries to prevent duplication
    Vehicle.objects.all().delete()

    filename = 'C:/Users/user/Documents/cars.csv'
    f = open(filename)
    f.readline()    #skip headers

    for line in f:
        fields = line.split(',')

        try:
            #create a new instance of the Vehicle using the current fields
            vehicle = Vehicle(make = fields[0],
                              model = fields[1],
                              year = fields[2],
                              body_type = fields[3],
                              engine_size = fields[4],
                              mpg = fields[5],
                              vin = fields[6],
                              msrp = fields[7].strip(),     #make sure we don't include newline characters
                              )
            vehicle.save() #commit to DB

        except:
            print(f'Skipped: {fields}') #catch any errors
    print(f'Done. Created {len(Vehicle.objects.all())} Vehicles')

def load_images():
    '''a function to assign images to vehicles
    this is only used for vehicles created from the csv
    Since each initial vehicle would be duplicate vehicles of the same make,
    we can assign this based solely on the vehicles make'''

    makes = Vehicle.objects.values_list('make', flat = True).distinct() #grab the list of all vehicle makes

    for make in makes:
        image_path = f'vehicles/{make.lower()}.jpg'     #all images used were just <make>.jpg
        
        #grab all vehicles of the current make, and update their images
        vehicles = Vehicle.objects.filter(make=make)
        updated = vehicles.update(image=image_path)

        print(f'Updated {updated} vehicles of make {make} with image {image_path}')
    
    #see how many vehicles have no images
    vehicles_no_image = Vehicle.objects.filter(image='').count()
    print(f'Done. {vehicles_no_image} vehicles could not get an image')



class Customer(models.Model):
    '''model representing a customer at the car dealership
    includes full name, drivers license id, credit score,
    date of birth, and a foreign key reference to the vehicle
    they are interested in (if any)'''
    
    first_name = models.TextField(blank = False)
    last_name = models.TextField(blank = False)
    credit_score = models.IntegerField(blank = True)
    license_id = models.IntegerField(blank = False)
    interested_in = models.ForeignKey(Vehicle, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def get_sales_match(self):
        '''return the salesmatch associated with this customer'''
        try:
            return SalesMatch.objects.get(customer=self)    #return salesmatches relating to this customer
        except:
            return None
        
    def get_absolute_url(self):
        '''method to direct newly registered users to their page'''
        return reverse('customer_details', kwargs = {'pk': self.pk})    #after creation, display current user

class Salesperson(models.Model):
    '''a model representing a salesperson at the dealership
    includes full name and years working at the company'''

    first_name = models.TextField(blank = False)
    last_name = models.TextField(blank = False)
    years_working = models.IntegerField(blank = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        '''method to direct the salesperson to the team list after creation'''
        return reverse('salesperson_details', kwargs={'pk': self.pk})    #after creation, display the user
    
    def get_reviews(self):
        '''accessor to return the reviews of a specific salesperson'''

        review = SalespersonReview.objects.filter(salesperson = self)      #grab all reviews relating to this salesperson

        return review
    
    def get_average_rating(self):
        '''a function to return the average review rating of a salesperson'''

        reviews = SalespersonReview.objects.filter(salesperson = self)

        if reviews:
            rating = 0

        #loop through all reviews, then average them out
            for r in reviews:
                rating += r.rating
            
            rating = rating / len(reviews)

            return round(rating, 1)
        else:
            return -1       #return -1 if there are no reviews, so we can determine this later in views

class SalesMatch(models.Model):
    '''a model representing a sale in progress
    includes a foreign key reference to a salesperson and 
    a customer, also includes the price as set by the salesperson'''

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    salesperson = models.ForeignKey(Salesperson, on_delete=models.CASCADE)
    price = models.IntegerField(blank = False)

class SalespersonReview(models.Model):
    '''a model to hold reviews of a specific salesperson
    includes a foreign key to the customer submitting the review,
    a foreign key to the salesperson being reviewed, a rating from
    1-5 as an integer, and some text for the review body'''

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    salesperson = models.ForeignKey(Salesperson, on_delete=models.CASCADE)
    rating = models.FloatField(blank = False, validators=[      #including some validators to ensure that the rating is from 1-5 inclusive
        MaxValueValidator(5.0),
        MinValueValidator(1.0)
    ])
    review_text = models.TextField(blank = False)

project/forms.py
from django import forms
from .models import *

#a file to provide forms for the project app
#All create and update actions will have forms stored here

class CreateSalesmatchForm(forms.ModelForm):
    '''A form which allows the salesperson to offer a price to an
    interested customer'''

    class Meta:
        model = SalesMatch
        fields = ['price']
        help_texts = {
            'price': "Enter a price in dollars",        #adding help text to describe the field
        }

class CreateSalespersonReviewForm(forms.ModelForm):
    '''a form which allows customers to submit reviews for salespeople'''

    class Meta:
        '''associate our form with a model in the DB'''
        model = SalespersonReview

        fields = ['rating', 'review_text']  #form should allow input of rating and review

class UpdateSalesmatchForm(forms.ModelForm):
    '''a form for updating the price of a salesmatch'''

    class Meta:
        '''associate form with model in our db and provide updatable
        fields'''

        model = SalesMatch

        fields = ['price']
        help_texts = {
            'price': 'Enter an updated price'   #describing the field
        }

class OfferDecisionForm(forms.ModelForm):
    '''a form to allow customers to accept or reject the sales
        offer'''
    
    decisions = [
        ('accept', 'Accept Offer'),
        ('reject', 'Reject Offer and continue searching')   #create decisions as radio buttons for this form
    ]
    decision = forms.ChoiceField(choices = decisions, widget = forms.RadioSelect)

    class Meta:
        model = SalesMatch
        fields = ['decision']

class CreateCustomerForm(forms.ModelForm):
    '''a form which allows the creation of a new customer'''

    class Meta:
        '''associate our form with a model in our DB'''

        model = Customer

        fields = ['first_name', 'last_name', 'credit_score', 'license_id'] #user must input all customer info

class CreateSalespersonForm(forms.ModelForm):
    '''a form to create a new salesperson'''
    #passkey allows us to ensure that anyone registering as a salesperson should actually be doing so
    passkey = forms.CharField(max_length = 50, required = True, widget = forms.PasswordInput)

    class Meta:
        '''associate with a model and provide fields
        includes a new field for a secret passkey to prevent
        random people from registering as a salesperson'''
        model = Salesperson

        fields = ['first_name', 'last_name', 'years_working']

class CreateVehicleForm(forms.ModelForm):
    '''a form to create a new vehicle'''

    class Meta:
        '''associating our form with model and providing fields'''

        model = Vehicle

        fields = ['vin', 'make', 'model', 'year', 'body_type', 'engine_size', 'mpg', 'msrp', 'image']

class CreateSalespersonReviewForm(forms.ModelForm):
    '''a form to allow customers to submit reviews for salespeople'''

    class Meta:
        '''associating with SalespersonReview model and adding fields'''

        model = SalespersonReview

        fields = ['rating', 'review_text']

class UpdateSalesReviewForm(forms.ModelForm):
    '''a form to update a review'''

    class Meta:
        '''associatatng with a model in our db'''

        model = SalespersonReview

        fields = ['rating', 'review_text']

project/templates/project/base.html
<!--Base page for linking in styles and proving 
content blocks to render content from other pages
also includes navigation section-->

{% load static %}

<html>
    <head>
        <title>Online Car Dealership</title>
        <link rel="stylesheet" href="{% static 'project/styles.css'%}">
    </head>
    <body>
        <header>
            <h1>Online Car Dealership</h1>
            {% if request.user.is_authenticated %}
            <p>Logged in as: {{request.user}}, {% if request.user.salesperson_set.exists%} Salesperson {%else%}, Customer{%endif%}</p>
            {% else %}
            <p>Not logged in</p>
            {%endif%}
            <nav>
                <ul>
                    <!--Links for users who are currently logged in-->
                    {% if request.user.is_authenticated %}
                    <li><form action="{% url 'logout' %}" method="POST">
                        {%csrf_token%}
                        <input type="submit" value="Logout">
                    </form></li>
                    <li><a href="{% url 'delete_account' %}">Delete my account</a></li>
                    <li><a href="{% url 'salesmatch_list' %}">Sales in progress</a></li>
                    <!--Links only for salespeople-->
                    {% if request.user.salesperson_set.exists %}
                    <li><a href="{% url 'customers' %}">People Currently Shopping</a></li>
                    <li><a href="{% url 'sold_vehicles' %}">Vehicles Sold</a></li>
                    <li><a href="{% url 'add_vehicle' %}">Add new vehicle</a></li>
                    {% endif %}
                    <!--Links for customers-->
                    {% if request.user.customer_set.exists %}
                    <li><a href="{% url 'customer_details' user.customer_set.first.pk%}">My Account</a></li>
                    {% endif %}
                    {% else %}
                    <!--Links that anyone can use-->
                    <li><a href="{% url 'login' %}">Login</a></li>
                    <li><a href="{% url 'register_customer'%}">Register as a customer</a></li>
                    <li><a href="{% url 'register_salesperson'%}">Register as a salesperson</a></li>
                    {% endif%}
                    <li><a href="{% url 'vehicle_list' %}">All vehicles</a></li>
                    <li><a href="{% url 'salespeople'%}">Meet the team</a></li>
                    <li><a href="{% url 'home' %}">Home and About</a></li>
                </ul>
            </nav>
        </header>

        {%block content%}
        {%endblock%}

    </body>
</html>

project/templates/project/create_sales_review.html
<!--A template for customers to submit reviews about salespeople-->

{% extends 'project/base.html' %}

{% block content %}

<h2>Reviewing {{salesperson.first_name}} {{salesperson.last_name}}</h2>

<div class = "row">
    <form method="POST">
        {%csrf_token%}
        <table>
            {{form.as_table}}   <!--Display the SalespersonReviewForm as a table-->
        </table>
        <input type="submit">
    </form>
    <form action="{% url 'salesperson_details' salesperson.pk%}">
        <input type="submit" value="Cancel">
    </form>
</div>

{% endblock %}

project/templates/project/create_salesmatch.html
<!--A template to create salesmatches, i.e. offer a price to a user-->

{% extends 'project/base.html' %}

{% block content %}

<div class="container">
    <h1>Create a sales offer</h1>
    <div class = 'row'>
        <!--Table of customer information-->
        <table>
            <tr>
                <th>Name</th>
                <td>{{customer.first_name}} {{customer.last_name}}</td>
            </tr>
            <tr>
                <th>Credit Score</th>
                <td>{{customer.credit_score}}</td>
            </tr>
            <tr>
                <th>Drivers License ID</th>
                <td>{{customer.license_id}}</td>
            </tr>
        </table>
    </div>
    <div class="row">
        <h4>Interested in:</h4>
        <table>
            <tr>
                <th>{{customer.interested_in.year}} {{customer.interested_in.make}} {{customer.interested_in.model}}</th>
                <td>MSRP: {{customer.interested_in.msrp}}</td>
            </tr>
        </table>
    </div>
    <!--This section allows salespeople to enter a price which will then create the SalesMatch object-->
    <div class = "row">
        <h4>Make an offer</h4>
        <form method = "POST">
            {% csrf_token %}
            {{form}}
            <input type="submit">
        </form>
        <form action="{% url 'customer_details' customer.pk%}">
            <input type="submit" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

project/templates/project/delete_account.html
<!--template which allows users to confirm their account's deletion-->

{% extends 'project/base.html' %}

{% block content %}

<div class = "container">
    <h2>Delete Account</h2>

    <p>Are you sure you want to delete your account?</p>

    <form method = "POST">
        {% csrf_token %}
        <button type="submit">Delete my account</button>
    </form>
</div>

{% endblock %}

project/templates/project/express_interest.html
<!--A template to confirm that a customers
interest expression has been successfully submitted-->

{% extends 'project/base.html' %}

{% block content %}

<div class = 'container'>
    <h1>You have successfully declared your interest in:</h1>
    <h3>{{v.year}} {{v.make}} {{v.model}}</h3>
    <h4>A representative will offer you a price shortly</h4>
</div>

{% endblock %}

project/templates/project/home.html
<!--Simple homepage template providing information
about the dealership to users-->

{% extends 'project/base.html'%}

{%block content %}
<div class = "container">
<h2>Welcome to the Dealership</h2>
<p>We are a completely online car dealership offering customers high quality vehicles!</p>
<p>To begin, create an account and view our vehicles currently in our inventory.</p>
<p>When you find one you like, select that you are interested and a sales representative will
    offer you a price, which you can accept or reject.
</p>
<p>If you don't like our first offer, feel free to continue browsing for vehicles we may be able to 
    offer a better price on!
</p>
</div>

{% endblock %}

project/templates/project/offer_accepted.html
<!--A confirmation view for an acceptance of a sales offer-->

{% extends 'project/base.html' %}

{% block content %}

<h1>Confirmation</h1>
<p>Thank you for your purchase! We hope you shop with us again in the future.</p>

{% endblock %}

project/templates/project/offer_rejected.html
<!--A confirmation view for rejection of a sales offer-->

{% extends 'project/base.html' %}

{% block content %}

<h1>Confirmation</h1>
<p>We're sorry we couldn't work out a deal for you.</p>
<p>Please consider declaring your interest in a different vehicle.</p>

{% endblock %}

project/templates/project/salesperson_detail.html
<!--A template to show the details of a single salesperson
also displays the reviews for that salesperson-->

{% extends 'project/base.html' %}

{% block content%}


<h2>Showing details for {{s.first_name}} {{s.last_name}}</h2>

<div class = 'container'>
    <div class = 'row'>
        <!--Table to display all salesperson info-->
        <table>
            <tr>
                <th>Name</th>
                <td>{{s.first_name}} {{s.last_name}}</td>
            </tr>
            <tr>
                <th>Years at the dealership</th>
                <td>{{s.years_working}}</td>
            </tr>
            <tr>
                <th>Average Rating</th>
                <td>{% if s.get_average_rating == -1 %} No ratings yet {% else %} {{s.get_average_rating}} {%endif%}</td>
            </tr>
        </table>
    </div>
    <!--An area to hold reviews of the salesperson. It also provides links to authenticated users
    (customers) to leave reviews and update and delete their own reviews-->
    <h2>Reviews</h2>
    <div class = "row">
        {% if request.user.customer_set.exists %}
        <a href="{% url 'salesperson_review' s.pk %}">Write a review</a>
        {% endif%}
        {% for r in s.get_reviews %}
        <div class = "review-container">
            <h4>From {{r.customer.first_name}} {{r.customer.last_name}}</h4>
            <h4>Rating: {{r.rating}}</h4>
            <p>{{r.review_text}}</p>
        </div>
        <div class = "update-buttons">
            {% if request.user == r.customer.user%}
            <h5><a href="{% url 'update_sales_review' r.pk%}">Update Review</a></h5>
            <h5><a href="{% url 'delete_sales_review' r.pk%}">Delete Review</a></h5>
            {% endif%}
        </div>
        <hr>
        {% endfor %}
    </div>
</div>


{% endblock %}

project/templates/project/salesperson_list.html
<!--a template to display a list of salespeople working
at the dealership-->

{% extends 'project/base.html' %}

{% block content %}
<div class = "container">
    <h1>Salespeople</h1>

    <!--providing pagination links for other pages-->
    <div class = "row">
        {% if is_paginated %}
        <ul class = "pagination">
            {%if page_obj.has_previous %}
            <li>
                <span><a href="?{{request.GET.urlencode}}&page={{page_obj.previous_page_number}}">Previous</a></span>
            </li>
            {% endif %}
            <li>
                <span>Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}.</span>
            </li>
            {% if page_obj.has_next %}
            <li>
                <span><a href="?{{request.GET.urlencode}}&page={{page_obj.next_page_number}}">Next</a></span>
            </li>
            {%endif%}
        </ul>
        {% endif%}
    </div>

    <!--Table showing all salespeople-->
    <div class = "row">
        <table>
            <tr>
                <th>Name</th>
                <th>Years at Dealership</th>
                <th>Rating</th>
            </tr>
            {% for s in salesperson%}
            <tr>
                <td>{{s.first_name}} {{s.last_name}}</td>
                <td>{{s.years_working}}</td>
                <td>{% if s.get_average_rating == -1%} No reviews {% else %} {{s.get_average_rating}} {%endif%}</td>
                <td><a href="{% url 'salesperson_details' s.pk%}">See Details and Reviews</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>


{%endblock%}

project/templates/project/salesperson_registration.html
<!--A view to allow salespeople to register at the dealership-->

{% extends 'project/base.html' %}

{% block content %}

<div class = "container">
    <h2>Register as a salesperson</h2>
    <p>Note: You will need to provide a passkey to complete this process.</p>

    <form method = "POST">
        {% csrf_token %}

        <h4>User Details</h4>
        <table>
            {{form.as_table}}   <!--Display the form for creating a Salesperson object-->
        </table>
        <hr>
        <hr>
        <h4>Account Details</h4>
        <table>
            {{user_creation_form.as_table}} <!--Display the form for django User objects-->
        </table>

        <input type="submit" value="Register as salesperson">
    </form>
</div>

{% endblock %}

project/templates/project/search.html
<!--an HTML template to provide search and filtering
will be included in vehicle_list.html-->

<h1>Filter vehicles</h1>

<table>
    <form action="{{request.path}}" method = "GET">
        <tr>
            <th>Vehicle Make</th>
            <td>
                <!--Filtering by make-->
                <select name="make" id="make">
                    <option value="" {% if not selected_make%} selected{%endif%}>--</option>
                    {% for make in makes %}
                    <option value="{{make}}" {% if make|stringformat:"s" == selected_make %}selected{%endif%}>{{make}}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Vehicle Model</th>
            <td>
                <!--Filtering by model-->
                <select name="model" id="model">
                    <option value="" {% if not selected_model %} selected {% endif %}>--</option>
                    {% for model in models %}
                    <option value="{{model}}" {% if model|stringformat:"s" == selected_model %}selected {%endif%}>{{model}}</option>
                    {%endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Vehicle Year</th>
            <!--Filtering by year-->
            <td>
                <select name="year" id="year">
                    <option value="" {% if not selected_year %}selected {%endif%}>--</option>
                    {% for year in years %}
                    <option value="{{year}}" {% if year|stringformat:"s" == selected_year %}selected {% endif%}>{{year}}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Vehicle Body</th>
            <td>
                <!--Filterin by body style-->
                <select name="body" id="body">
                    <option value=""{% if not selected_body %}selected {%endif%}>--</option>
                    {% for body in bodies%}
                    <option value="{{body}}" {% if body|stringformat:"s" == selected_body %}selected {%endif%}>{{body}}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Number of Cylinders</th>
            <td>
                <!--Filtering by engine size-->
                <select name="engine" id="engine">
                    <option value="" {% if not selected_engine %} selected {% endif %}>--</option>
                    {% for engine in engines %}
                    <option value="{{engine}}" {% if engine|stringformat:"s" == selected_engine %}selected {%endif%}>{{engine}} cylinders</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Max MSRP</th>
            <td>
                <!--Filtering by max MSRP (all vehicles under the selected value will be shown)-->
                <select name="max_msrp" id="max_msrp">
                    <option value="" {% if not max_msrp %} selected {% endif %}>--</option>
                    {% for msrp in msrps %}
                    <option value="{{msrp}}" {% if msrp|stringformat:"s" == max_msrp %} selected {% endif%}>${{msrp}}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <th>Minimum MPG</th>
            <td>
                <!--Filtering by min mpg (all vehicles above this value will be shown)-->
                <select name="min_mpg" id="min_mpg">
                    <option value="" {% if not min_mpg %} selected {% endif%}>--</option>
                    {% for mpg in mpgs %}
                    <option value="{{mpg}}" {% if mpg|stringformat:"s" == min_mpg %} selected {% endif %}>{{mpg}} miles per gallon</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td><input type="submit"></td>
            <td></td>
        </tr>
    </form>
</table>

project/templates/project/update_salesmatch_form.html
<!--A view to display a form to update a salesmatch object-->

{% extends 'project/base.html' %}

{% block content %}

<div class = "container">
    <h1>Update Sales Offer</h1>
    <div class = "row">
        <form method = "POST">
            {% csrf_token %}
            {{form.as_table}}        <!--Display the update form as a table-->
            <input type="submit">
        </form>
        <form action="{% url 'salesmatch_detail' salesmatch.pk%}">
            <input type="submit" value="Cancel">
        </form>
    </div>
</div>

{% endblock %}

project/templates/project/wrong_passkey.html
<!--A template for when a user tries to register as a salesperson 
but enters the wrong passkey-->

{% extends 'project/base.html' %}

{% block content %}

<h1>Invalid passkey</h1>
<p>The passkey you provided is not valid to register as a salesperson</p>
<p>Please try again, or register as a customer instead</p>

{% endblock%}